### ISSUE TITLE
Custom shaders for SKVideoNode

### ISSUE THREAD

**Issue by alexfoxy** [gsabran/DDDKit#4]
Hi,

I'm planning on using SpriteKit for an app but I noticed they don't allow custom shaders / filters for the SKVideoNode class.

Upon Googling I came across your custom library for SceneKit and noticed you have written your own video texture implementation. Does this allow you to apple custom GL shaders to videos and do you think it would be possible to port your video texture implementation to work with SpriteKit?

Thanks!

Alex

**Comment by gsabran** [comment]
Hi Alex,

Yes you can apply custom shaders to videos using DDDKit. That was my main motivation since it was not working or buggy on SceneKit and SpriteKit when I needed it. The downside is that it's either one or the other library and I don't see a solution for using a bit of both. So if you decide to use DDDKit you'll have to be sure you won't need some of the other nice features SpriteKit has.

I'd say that DDDKit works well for simple displays. I've used it mainly for 360 videos. If you've a complex scene to render I'd do a toy project to test the potential before committing to using the framework.
